[package]
name = "ledger-lsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ledger-parser = "6.0.0"
log = "0.4.21"
regex = "1.10.4"
serde = { version = "1", features = ["serde_derive"] }
serde_json = { version = "1" }
simple-logging = "2.0.2"
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "io-std",
    "macros",
] }
tower-lsp = { version = "0.20", features = ["runtime-tokio"] }
