name: test

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - '**'

env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: rustup update
      - run: rustup default stable
      - run: rustup component add clippy
      - run: rustup component add rustfmt

      - name: Check formatting
        run: cargo fmt --check

      - name: Check clippy
        run: cargo clippy -- --deny warnings

  tests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: rustup update
      - run: rustup default stable

      - name: Compile
        run: cargo build --tests --verbose

      - name: Test
        run: |
          export RUST_BACKTRACE=1
          cargo test --verbose --no-fail-fast
